---
apiVersion: v1
kind: Service
metadata:
  name: ssv-liquidator-worker-3-svc
  namespace: REPLACE_NAMESPACE 
  labels:
    name: ssv-liquidator-worker-3-svc
spec:
  type: ClusterIP 
  ports:
    - port: 80 
      protocol: TCP
      targetPort: 3000
  selector:
    app: ssv-liquidator-worker-3
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-liquidator-worker-3
  name: ssv-liquidator-worker-3
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  selector:
    matchLabels:
      app: ssv-liquidator-worker-3
  template:
    metadata:
      labels:
        app: ssv-liquidator-worker-3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main      
      containers:
      - name: ssv-liquidator-worker-3
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        command: ["/bin/sh"]
        args: ["-c", "yarn cli"]
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: node_env         
              
        - name: NODE_URL
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: node_url

        - name: GAS_PRICE
          value: "normal"

        - name: SSV_NETWORK_ADDRESS
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_network_address

        - name: ACCOUNT_PRIVATE_KEY_3
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: account_private_key_3

        - name: SSV_TOKEN_ADDRESS
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_token_address

        volumeMounts:
        - mountPath: "/data/"
          name: ssv-liquidator-worker-3
      volumes:
      - persistentVolumeClaim:
          claimName: ssv-liquidator-worker-3         
        name: ssv-liquidator-worker-3
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
