---
apiVersion: v1
kind: Service
metadata:
  name: ssv-liquidator-worker-svc
  namespace: REPLACE_NAMESPACE
  labels:
    name: ssv-liquidator-worker-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3030
  selector:
    app: ssv-liquidator-worker
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-liquidator-worker
  name: ssv-liquidator-worker
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  selector:
    matchLabels:
      app: ssv-liquidator-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ssv-liquidator-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
      containers:
      - name: ssv-liquidator-worker
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        ports:
        - containerPort: 3030
        command: ["/bin/sh"]
        args: ["-c", "yarn cli"]
        env:
        - name: WORKER_PORT
          value: "3030"

        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: node_env

        - name: NODE_URL
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: node_url

        - name: GAS_PRICE
          value: "normal"

        - name: SSV_NETWORK_ADDRESS
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_network_address

        - name: ACCOUNT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: account_private_key

        volumeMounts:
        - mountPath: "/data/"
          name: ssv-liquidator-worker
      volumes:
      - persistentVolumeClaim:
          claimName: ssv-liquidator-worker
        name: ssv-liquidator-worker
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
