version: '3'

services:
  worker:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "yarn start"
    volumes:
      - sqlite-data:/opt/app/data
    environment:
      - SSV_NETWORK_ADDRESS
      - NODE_URL
      - ACCOUNT_ADDRESS
      - ACCOUNT_PRIVATE_KEY
      - GAS_PRICE
      - ETHERSCAN_KEY
    restart: on-failure

volumes:
  sqlite-data:
