version: '3'

services:
  worker:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "yarn start:prod:worker"
    volumes:
      - sqlite-data:/opt/app/data
    ports:
      - '$WORKER_PORT:$WORKER_PORT'
    environment:
      - WORKER_PORT
      - NODE_ENV
      - SSV_NETWORK_ADDRESS
      - NODE_URL
      - ACCOUNT_ADDRESS
      - ACCOUNT_PRIVATE_KEY
      - LIQUIDATE_BATCH_SIZE
      - GAS
      - GAS_PRICE
    restart: on-failure

volumes:
  sqlite-data:
