version: '3'

services:
  worker:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "yarn cli"
    volumes:
      - sqlite-data:/opt/app/data
    environment:
      - SSV_NETWORK_ADDRESS
      - NODE_URL
      - ACCOUNT_PRIVATE_KEY
      - GAS_PRICE
      - HIDE_TABLE
      - NODE_RATE_LIMIT
      - LOG_LEVEL
      - NO_COLOR
    restart: on-failure

volumes:
  sqlite-data:
