---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssv-liquidator-api
  namespace: liquidation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
