# Default values for contract-center-worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: liquidation

image:
  repository: 764289642555.dkr.ecr.us-west-2.amazonaws.com/ssv-liquidator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1500m
    memory: 4096Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/role
              operator: In
              values:
                - ssv-main
tolerations:
  - effect: NoSchedule
    key: kubernetes.io/role
    operator: Exists
