# Default values for contract-center-worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 
  ssv_liquidator_worker: 1
  ssv_liquidator_worker_2: 1
  ssv_liquidator_worker_3: 1
  ssv_liquidator_worker_4: 1
  ssv_liquidator_worker_5: 1
  ssv_liquidator_worker_6: 1
  ssv_liquidator_worker_7: 1
  ssv_liquidator_worker_8: 1
  ssv_liquidator_worker_9: 1

namespace: liquidation

app:
  logLevel: 'debug'
  noColor: 'true'

image:
  repository: 764289642555.dkr.ecr.us-west-2.amazonaws.com/ssv-liquidator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1500m
    memory: 2048Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/role
              operator: In
              values:
                - ssv-main
tolerations:
  - effect: NoSchedule
    key: kubernetes.io/role
    operator: Exists
