# Default values for contract-center-worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  liquidator_holesky_j2_1: 1
  liquidator_mainnet_1: 0
  liquidator_mainnet_2: 0
  liquidator_mainnet_3: 0

namespace: liquidation

app:
  logLevel: 'debug'
  noColor: 'true'

image:
  repository: 121827225315.dkr.ecr.us-west-2.amazonaws.com/ssv-liquidator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 400m
    memory: 2048Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/role
              operator: In
              values:
                - ssv-main
tolerations:
  - effect: NoSchedule
    key: kubernetes.io/role
    operator: Exists
