---
apiVersion: v1
kind: Service
metadata:
  name: liquidator-holesky-jato-v2-1-svc
  namespace: {{ .Values.namespace }}
  labels:
    name: liquidator-holesky-jato-v2-1-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: liquidator-holesky-jato-v2-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: liquidator-holesky-jato-v2-1
  name: liquidator-holesky-jato-v2-1
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.liquidator_holesky_j2_1 }}
  selector:
    matchLabels:
      app: liquidator-holesky-jato-v2-1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: liquidator-holesky-jato-v2-1
    spec:
      containers:
      - name: liquidator-holesky-jato-v2-1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        command: ["/bin/sh"]
        args: ["-c", "yarn cli"]
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: node_env

        - name: LOG_LEVEL
          value: "{{ .Values.app.logLevel }}"

        - name: NO_COLOR
          value: "{{ .Values.app.noColor }}"

        - name: NODE_URL
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: node_url_holesky

        - name: GAS_PRICE
          value: "medium"

        - name: HIDE_TABLE
          value: "1"

        - name: ACCOUNT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: account_private_key_liquidator_holesky_j2_1

        - name: SSV_SYNC_ENV
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_sync_env_holesky

        - name: SSV_SYNC
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_sync_holesky

#        volumeMounts:
#        - mountPath: "/data/"
#          name: liquidator-holesky-jato-v2-1
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
#      volumes:
#      - persistentVolumeClaim:
#          claimName: liquidator-holesky-jato-v2-1
#        name: liquidator-holesky-jato-v2-1
        {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
