---
apiVersion: v1
kind: Service
metadata:
  name: liquidator-mainnet-3-svc
  namespace: {{ .Values.namespace }}
  labels:
    name: liquidator-mainnet-3-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: liquidator-mainnet-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: liquidator-mainnet-3
  name: liquidator-mainnet-3
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.liquidator_mainnet_3 }}
  selector:
    matchLabels:
      app: liquidator-mainnet-3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: liquidator-mainnet-3
    spec:
      containers:
      - name: liquidator-mainnet-3
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        command: ["/bin/sh"]
        args: ["-c", "yarn cli"]
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: node_env

        - name: LOG_LEVEL
          value: "{{ .Values.app.logLevel }}"

        - name: NO_COLOR
          value: "{{ .Values.app.noColor }}"

        - name: NODE_URL
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: node_url_9

        - name: GAS_PRICE
          value: "high"

        - name: HIDE_TABLE
          value: "1"

        - name: ACCOUNT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: account_private_key_3

        - name: SSV_SYNC_ENV
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_sync_env_9

        - name: SSV_SYNC
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_sync_9


#        volumeMounts:
#        - mountPath: "/data/"
#          name: liquidator-mainnet-3
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
#      volumes:
#      - persistentVolumeClaim:
#          claimName: liquidator-mainnet-3
#        name: liquidator-mainnet-3
        {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
