---
apiVersion: v1
kind: Service
metadata:
  name: ssv-liquidator-worker-5-svc
  namespace: {{ .Values.namespace }}
  labels:
    name: ssv-liquidator-worker-5-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: ssv-liquidator-worker-5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssv-liquidator-worker-5
  name: ssv-liquidator-worker-5
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ssv-liquidator-worker-5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ssv-liquidator-worker-5
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
      containers:
      - name: ssv-liquidator-worker-5
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        command: ["/bin/sh"]
        args: ["-c", "yarn cli"]
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: node_env

        - name: LOG_LEVEL
          value: "{{ .Values.app.logLevel }}"

        - name: NO_COLOR
          value: "{{ .Values.app.noColor }}"

        - name: NODE_URL
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: node_url

        - name: GAS_PRICE
          value: "medium"

        - name: SSV_NETWORK_ADDRESS
          valueFrom:
            secretKeyRef:
              name: config-secrets
# Jato2 v0.3.1-rc
              key: ssv_network_address_5

        - name: HIDE_TABLE
          value: "1"

        - name: SSV_NETWORK_VIEWS_ADDRESS
          valueFrom:
            secretKeyRef:
              name: config-secrets
# Jato2 v0.3.1-rc
              key: ssv_network_views_address_5

        - name: ACCOUNT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: account_private_key_2

        - name: SSV_TOKEN_ADDRESS
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_token_address

#        volumeMounts:
#        - mountPath: "/data/"
#          name: ssv-liquidator-worker-5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
#      volumes:
#      - persistentVolumeClaim:
#          claimName: ssv-liquidator-worker-5
#        name: ssv-liquidator-worker-5
        {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
