---
apiVersion: v1
kind: Service
metadata:
  name: ssv-liquidator-worker-svc
  namespace: {{ .Values.namespace }}
  labels:
    name: ssv-liquidator-worker-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: ssv-liquidator-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssv-liquidator-worker
  name: ssv-liquidator-worker
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ssv-liquidator-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ssv-liquidator-worker
    spec:
      containers:
      - name: ssv-liquidator-worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        command: ["/bin/sh"]
        args: ["-c", "yarn cli"]
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: node_env
              
        - name: NODE_URL
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: node_url

        - name: GAS_PRICE
          value: "medium"

        - name: SSV_NETWORK_ADDRESS
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_network_address

        - name: HIDE_TABLE
          value: "1"

        - name: SSV_NETWORK_VIEWS_ADDRESS
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_network_views_address

        - name: ACCOUNT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: account_private_key

        - name: SSV_TOKEN_ADDRESS
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_token_address

#        volumeMounts:
#        - mountPath: "/data/"
#          name: ssv-liquidator-worker
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
#      volumes:
#      - persistentVolumeClaim:
#          claimName: ssv-liquidator-worker
#        name: ssv-liquidator-worker
        {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
